# Generated by Django 5.0.2 on 2024-02-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(blank=True, to="projects.tag"),
        ),
    ]
