# Generated by Django 5.0.2 on 2024-02-27 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_project_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="project",
            field=models.ForeignKey(
                default="181697c7cb8644399026e3afad514644",
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
            preserve_default=False,
        ),
    ]
